plugins {
    id "com.android.application"
}

def appVersionName = project.findProperty("appVersionName") ?: "1.0.0"
def appVersionCode = (project.findProperty("appVersionCode") ?: "10000") as Integer

android {
    namespace "com.pocketkaraoke"
    compileSdk 35

    defaultConfig {
        applicationId "com.pocketkaraoke"
        minSdk 23
        targetSdk 35
        versionCode appVersionCode
        versionName appVersionName
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
